# Set 2: Customer Feedback Analysis
customers <- data.frame(id = 1:5, age = c(25, 30, 35, 28, 40), satisfaction = c(4, 5, 3, 4, 5))
feedback <- c("helpful service", "very helpful support", "good experience", "quick service", "excellent support")
customers$age_group <- cut(customers$age, breaks = c(19, 29, 39, Inf), labels = c("20-29", "30-39", "40+"))
old <- par(mfrow = c(2, 2), mar = c(5, 4, 3, 1))
hist(customers$age, breaks = seq(20, 45, 5), xlab = "Age", ylab = "Customers", main = "Customer Age Distribution", col = "skyblue")
pie(table(customers$satisfaction), main = "Satisfaction Scores", col = heat.colors(5), labels = paste(names(table(customers$satisfaction)), "(", as.vector(table(customers$satisfaction)), ")"))
score_by_age <- table(customers$age_group, factor(customers$satisfaction, levels = 1:5))
barplot(t(score_by_age), beside = FALSE, xlab = "Age group", ylab = "Customers", main = "Scores by Age Group", col = rainbow(5), legend.text = colnames(score_by_age))
words <- unlist(strsplit(tolower(gsub("[^[:alpha:] ]", "", feedback)), " +"))
word_counts <- sort(table(words), decreasing = TRUE)
barplot(head(word_counts, 8), las = 2, ylab = "Frequency", main = "Frequent Feedback Words", col = "orchid")
par(old)
print(customers)
