# Set 8: Employee Performance Analysis
employees <- data.frame(id = 1:3, department = c("Sales", "HR", "Marketing"), years = c(5, 3, 7), score = c(85, 92, 78))
old <- par(mfrow = c(1, 3), mar = c(5, 4, 3, 1))
plot(employees$id, employees$score, type = "b", pch = 19, xaxt = "n", xlab = "Employee ID", ylab = "Performance score", main = "Scores by Employee", col = "steelblue")
axis(1, at = employees$id, labels = employees$id)
barplot(table(employees$department), las = 2, xlab = "Department", ylab = "Employees", main = "Department Counts", col = "darkseagreen3")
plot.new(); title("Employee Performance Table")
text(.05, .9, paste(capture.output(print(employees, row.names = FALSE)), collapse = "\n"), adj = c(0, 1), family = "mono", cex = .65)
par(old)
print(employees)
